<?php

namespace wockkinmycup\Apotheosis;

use pocketmine\plugin\PluginBase;
use wockkinmycup\Apotheosis\Modules\Adventure\Listeners\AffixListener;
use wockkinmycup\Apotheosis\Utils\Utils;

class Loader extends PluginBase {

    public static Loader $instance;

    public function onLoad(): void
    {
        self::$instance = $this;
    }

    public function onEnable(): void
    {
        $this->registerListeners();
    }

    public function onDisable(): void
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }

    public function registerListeners() {
        $pMngr = $this->getServer()->getPluginManager();

        // Adventure Module
        if (Utils::getConfig()->getNested("modules.adventure") === true) {
            $pMngr->registerEvents(new AffixListener(), $this);
            $this->getLogger()->notice("Adventure Module Enabled!");
        }
    }

    public static function getInstance() : Loader {
        return self::$instance;
    }
}
