<?php

namespace wockkinmycup\Apotheosis;

use pocketmine\plugin\PluginBase;
use wockkinmycup\Apotheosis\Modules\Adventure\Listeners\AffixListener;

class Loader extends PluginBase {

    public static Loader $instance;

    public function onLoad(): void
    {
        self::$instance = $this;
    }

    public function onEnable(): void
    {
        $this->registerListeners();
    }

    public function onDisable(): void
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }

    public function registerListeners() {
        $pMngr = $this->getServer()->getPluginManager();

        $pMngr->registerEvents(new AffixListener(), $this);
    }

    public static function getInstance() : Loader {
        return self::getInstance();
    }
}
